import logging
from typing import Any, Optional

from services.planner.planning_models import PlanGoal, Task
from services.planner.strategies.strategy_base import Strategy
from services.planner.strategies.planning_registry import select_strategy

logger = logging.getLogger(__name__)


def generate_tasks(
    goal: PlanGoal,
    context: dict[str, Any],
    strategy: Optional[Strategy] = None,
) -> list[Task]:
    if strategy is None:
        strategy = select_strategy(goal)
    if strategy is None:
        logger.error("No strategy available for goal: %s", goal.target_action)
        return []

    logger.info(
        "Generating tasks using strategy '%s' for goal '%s'",
        strategy.name,
        goal.target_action,
    )
    tasks = strategy.generate_tasks(goal, context)

    for task in tasks:
        if not task.reasoning_goal:
            task.reasoning_goal = goal.target_action
        if not task.reasoning_trace:
            task.reasoning_trace = f"Generated by strategy '{strategy.name}'"

    logger.info("Generated %d tasks from strategy '%s'", len(tasks), strategy.name)
    return tasks
