from __future__ import annotations

"""Launch foundation persistence: canonical tables + repositories.

Additive, owned by the 005-010 migrations. Kept separate from the existing
persistence repositories until each domain absorbs its entities.
"""

from .models import (
    ProviderPayload,
    AuditRecord,
    Campaign,
    CampaignLead,
    Company,
    ConnectedAccount,
    Draft,
    ExternalIdentity,
    Knowledge,
    Lead,
    LeadSignal,
    LeadSource,
    Notification,
    Plan,
    PlanFeature,
    Strategy,
    Subscription,
    UsageRecord,
    Workspace,
    WorkspaceCompany,
    WorkspaceLead,
    WorkspaceMember,
)
from .repositories import (
    AuditLogRepository,
    CampaignLeadRepository,
    CampaignRepository,
    CompanyRepository,
    ConnectedAccountRepository,
    DraftRepository,
    ExternalIdentityRepository,
    KnowledgeRepository,
    LeadRepository,
    LeadSignalRepository,
    LeadSourceRepository,
    NotificationRepository,
    PlanFeatureRepository,
    PlanRepository,
    ProviderPayloadRepository,
    StrategyRepository,
    SubscriptionRepository,
    UsageRecordRepository,
    WorkspaceMemberRepository,
    WorkspaceCompanyRepository,
    WorkspaceLeadRepository,
    WorkspaceRepository,
)
from .backfill import backfill_all, backfill_workspace

__all__ = [
    "AuditRecord",
    "Campaign",
    "CampaignLead",
    "Company",
    "ConnectedAccount",
    "Draft",
    "ExternalIdentity",
    "Knowledge",
    "Lead",
    "LeadSignal",
    "LeadSource",
    "Notification",
    "Plan",
    "PlanFeature",
    "ProviderPayload",
    "Strategy",
    "Subscription",
    "UsageRecord",
    "Workspace",
    "WorkspaceCompany",
    "WorkspaceLead",
    "WorkspaceMember",
    "AuditLogRepository",
    "CampaignLeadRepository",
    "CampaignRepository",
    "CompanyRepository",
    "ConnectedAccountRepository",
    "DraftRepository",
    "ExternalIdentityRepository",
    "KnowledgeRepository",
    "LeadRepository",
    "LeadSignalRepository",
    "LeadSourceRepository",
    "NotificationRepository",
    "PlanFeatureRepository",
    "PlanRepository",
    "ProviderPayloadRepository",
    "StrategyRepository",
    "SubscriptionRepository",
    "UsageRecordRepository",
    "WorkspaceMemberRepository",
    "WorkspaceCompanyRepository",
    "WorkspaceLeadRepository",
    "WorkspaceRepository",
]