"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { listWorkspaceLeads, type WorkspaceLeadRecord } from "../../../lib/api";

const token = () => localStorage.getItem("loqi_active_session_token") || "";
const FILTERS = [{ key: "location", label: "Location" }, { key: "industry", label: "Industry" }, { key: "company", label: "Company name" }, { key: "title", label: "Job title" }];

export default function DiscoverPage() {
  const router = useRouter(); const params = useSearchParams(); const [leads, setLeads] = useState<WorkspaceLeadRecord[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selected, setSelected] = useState<Set<string>>(new Set());
  const q = params.get("q") || ""; const filters = Object.fromEntries(FILTERS.map(({ key }) => [key, params.get(key) || ""]));
  const page = Math.max(Number(params.get("page") || "1") || 1, 1); const pageSize = 50;
  const update = (next: Record<string, string>) => router.replace(`/discover?${new URLSearchParams(next).toString()}`);
  const updateSearch = (next: Record<string, string>) => update({ ...next, page: "1" });
  useEffect(() => { let active = true; setLoading(true); setError(""); void listWorkspaceLeads(token(), q, page, filters).then((r) => { if (active) { setLeads(r.leads); setTotal(r.total); } }).catch(() => { if (active) { setLeads([]); setTotal(0); setError("Could not load leads. Please try again."); } }).finally(() => active && setLoading(false)); return () => { active = false; }; }, [q, JSON.stringify(filters), page]);
  const all = leads.length > 0 && leads.every((lead) => selected.has(lead.id));
  return <main className="p-8 space-y-6"><header><h1 className="text-3xl font-semibold">Discover</h1><p className="text-sm text-on-surface-variant">Search and filter leads already in your workspace.</p></header>
    <input className="w-full rounded-xl border bg-surface p-4 text-lg" value={q} placeholder="Search people, companies, titles, websites..." onChange={(e) => updateSearch({ ...filters, q: e.target.value })}/>
    <div><p className="text-sm font-medium mb-2">Suggested for you</p><div className="flex gap-2 flex-wrap">{["SaaS", "Operations leaders", "United States"].map((suggestion) => <button key={suggestion} onClick={() => updateSearch({ ...filters, q: suggestion })} className="rounded-full border px-3 py-1 text-sm">{suggestion}</button>)}</div></div>
    <div className="grid lg:grid-cols-[240px_1fr] gap-6"><aside className="rounded-xl border p-4 space-y-4"><div className="flex justify-between"><b>Filters</b><button className="text-sm text-primary" onClick={() => update({ q: "", page: "1" })}>Clear all</button></div>{FILTERS.map(({ key, label }) => <label key={key} className="block text-sm"><span>{label}</span><input className="mt-1 w-full rounded border p-2" value={filters[key]} onChange={(e) => updateSearch({ ...filters, q, [key]: e.target.value })}/></label>)}</aside>
      <section className="space-y-3"><div className="flex justify-between"><span>{total} lead{total === 1 ? "" : "s"}</span>{selected.size > 0 && <div className="flex gap-2"><span className="text-sm text-primary">{selected.size} selected</span><button className="rounded bg-primary px-3 py-1 text-on-primary" onClick={() => router.push(`/lead-intelligence?lead_ids=${encodeURIComponent([...selected].join(","))}`)}>Analyze with Loqi</button><button className="text-sm text-primary" onClick={() => setSelected(new Set())}>Clear selection</button></div>}</div>{error ? <p className="rounded-xl border border-error/30 p-4 text-error">{error}</p> : loading ? <p>Loading results…</p> : leads.length === 0 ? <p className="rounded-xl border p-10 text-center">{q || Object.values(filters).some(Boolean) ? "No leads match these filters." : "Your lead database is empty. Import a CSV to get started."}</p> : <><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3"><input type="checkbox" checked={all} onChange={() => setSelected((current) => { const next = new Set(current); leads.forEach((lead) => all ? next.delete(lead.id) : next.add(lead.id)); return next; })}/></th><th>Name</th><th>Email</th><th>Company</th><th>Title</th><th>Website</th><th>Location</th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id} className="border-b"><td className="p-3"><input type="checkbox" checked={selected.has(lead.id)} onChange={() => setSelected((s) => { const n = new Set(s); n.has(lead.id) ? n.delete(lead.id) : n.add(lead.id); return n; })}/></td><td>{`${lead.first_name} ${lead.last_name}`.trim() || "—"}</td><td>{lead.email || "—"}</td><td>{lead.company || "—"}</td><td>{lead.title || "—"}</td><td>{lead.website || "—"}</td><td>{lead.location || "—"}</td></tr>)}</tbody></table></div>{total > pageSize && <nav className="flex items-center justify-between" aria-label="Lead results pagination"><button disabled={page === 1} onClick={() => update({ ...filters, q, page: String(page - 1) })} className="rounded border px-3 py-1 disabled:opacity-50">Previous</button><span className="text-sm text-on-surface-variant">Page {page}</span><button disabled={page * pageSize >= total} onClick={() => update({ ...filters, q, page: String(page + 1) })} className="rounded border px-3 py-1 disabled:opacity-50">Next</button></nav>}</>}</section></div></main>;
}
